volumes:
  dbdata:
    labels:
      - "@nicholasray/pixel=0.0.0"
  mwcode:
    labels:
      - "@nicholasray/pixel=0.0.0"
  vrdata:
    labels:
      - "@nicholasray/pixel=0.0.0"
services:
  mediawiki:
    env_file:
      - .env
    environment:
      COMPOSER_CACHE_DIR: /var/www/html/w/cache/composer
    volumes:
      - mwcode:/var/www/html/w
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ CMD, php-fpm-healthcheck ]
      interval: 5s
      timeout: 1s
      retries: 10
  mediawiki-web:
    image: docker-registry.wikimedia.org/dev/buster-apache2:2.0.0
    env_file:
      - .env
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    ports:
      - "${MW_DOCKER_PORT}:8080"
    volumes:
      - mwcode:/var/www/html/w
    depends_on:
      mediawiki:
        condition: service_healthy
    healthcheck:
      test: [ CMD, curl, -f, http://localhost:8080/wiki/Main_Page ]
      interval: 5s
      timeout: 5s
      retries: 10
  database:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ CMD, mysqladmin, ping, -h, localhost ]
      interval: 5s
      timeout: 5s
      retries: 10
  visual-regression:
    network_mode: host
    env_file:
      - .env
    volumes:
      - vrdata:/vrdata
    depends_on:
      mediawiki-web:
        condition: service_healthy
  visual-regression-reporter:
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - vrdata:/vrdata
