volumes:
  dbdata:
    name: pixel_dev_dbdata
  mwcode:
    name: pixel_dev_mwcode
  vrdata:
    name: pixel_dev_vrdata
services:
  mediawiki:
    image: pixel_mediawiki:0.0.0
    build:
      context: .
      dockerfile: Dockerfile.mediawiki
    volumes:
      - ./LocalSettings.php:/var/www/html/w/LocalSettings.php
      - ./src:/src
  database:
    image: pixel_database:0.0.0
    build:
      context: .
      dockerfile: Dockerfile.database
    volumes:
      - ./src/seedDb.sh:/docker-entrypoint-initdb.d/seedDb.sh
  visual-regression:
    image: pixel_visual-regression:0.0.0
    build:
      context: .
      dockerfile: Dockerfile.visual-regression
    volumes:
      - .:/pixel/
  visual-regression-reporter:
    image: pixel_visual-regression-reporter:0.0.0
    build:
      context: .
      dockerfile: Dockerfile.visual-regression-reporter
