services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile.mediawiki
    volumes:
      - ./LocalSettings.php:/var/www/html/w/LocalSettings.php
      - ./src:/src
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    volumes:
      - ./src/seedDb.sh:/docker-entrypoint-initdb.d/seedDb.sh
  visual-regression:
    build:
      context: .
      dockerfile: Dockerfile.visual-regression
    volumes:
      - ./src:/pixel/src
      - ./viewports.js:/pixel/viewports.js
      - ./configDesktop.js:/pixel/configDesktop.js
      - ./configEcho.js:/pixel/configEcho.js
      - ./configMobile.js:/pixel/configMobile.js
  visual-regression-reporter:
    build:
      context: .
      dockerfile: Dockerfile.visual-regression-reporter
