name: Lint, Build, Test

on: 
  workflow_call:
    inputs:
      run_vr:
        required: false
        type: boolean
        description: Whether or not the vr tests should run.
        default: true

jobs:
  build:
    name: Lint, test, and run visual regression tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Run visual regression
      if: ${{ inputs.run_vr == true }}
      shell: 'script -q -e -c "bash {0}"'
      run: |
        script -e -c "./pixel.js reference && ./pixel.js test"
